from flask import Blueprint, render_template, send_file
from flask_login import login_required, current_user

from reportlab.pdfgen import canvas
from reportlab.lib.colors import red, black

from openpyxl import Workbook

from io import BytesIO
from datetime import datetime

from models.models import UploadedFile, ThreatLog


report = Blueprint(
    "report",
    __name__
)


# =====================================================
# Report Dashboard
# =====================================================

@report.route("/report")
@login_required
def report_page():

    total_files = UploadedFile.query.count()

    total_threats = ThreatLog.query.count()

    high_risk = ThreatLog.query.filter_by(
        severity="High"
    ).count()

    low_risk = ThreatLog.query.filter_by(
        severity="Low"
    ).count()

    threats = ThreatLog.query.order_by(
        ThreatLog.detected_at.desc()
    ).all()

    return render_template(
        "report.html",

        total_files=total_files,
        total_threats=total_threats,

        high_risk=high_risk,
        low_risk=low_risk,

        threats=threats
    )


# =====================================================
# PDF REPORT
# =====================================================

@report.route("/report/pdf")
@login_required
def generate_pdf():

    buffer = BytesIO()

    pdf = canvas.Canvas(buffer)

    pdf.setTitle("CloudShield AI Security Report")

    width, height = pdf._pagesize

    # Header

    pdf.setFont("Helvetica-Bold", 22)
    pdf.setFillColor(red)

    pdf.drawString(
        50,
        height - 50,
        "CloudShield AI"
    )

    pdf.setFillColor(black)

    pdf.setFont("Helvetica-Bold", 16)

    pdf.drawString(
        50,
        height - 80,
        "Cloud Threat Detection Report"
    )

    pdf.setFont("Helvetica", 11)

    pdf.drawString(
        50,
        height - 105,
        f"Generated By : {current_user.fullname}"
    )

    pdf.drawString(
        50,
        height - 125,
        f"Date : {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}"
    )

    # Statistics

    total_files = UploadedFile.query.count()

    total_threats = ThreatLog.query.count()

    critical = ThreatLog.query.filter_by(
        severity="Critical"
    ).count()

    high = ThreatLog.query.filter_by(
        severity="High"
    ).count()

    medium = ThreatLog.query.filter_by(
        severity="Medium"
    ).count()

    low = ThreatLog.query.filter_by(
        severity="Low"
    ).count()

    y = height - 170

    pdf.setFont("Helvetica-Bold", 13)

    pdf.drawString(
        50,
        y,
        "Security Summary"
    )

    y -= 25

    pdf.setFont("Helvetica", 11)

    pdf.drawString(60, y, f"Total Files : {total_files}")
    y -= 18

    pdf.drawString(60, y, f"Total Threats : {total_threats}")
    y -= 18

    pdf.drawString(60, y, f"Critical : {critical}")
    y -= 18

    pdf.drawString(60, y, f"High : {high}")
    y -= 18

    pdf.drawString(60, y, f"Medium : {medium}")
    y -= 18

    pdf.drawString(60, y, f"Low : {low}")

    # Threat Table

    y -= 45

    pdf.setFont("Helvetica-Bold", 12)

    pdf.drawString(50, y, "Filename")
    pdf.drawString(250, y, "Severity")
    pdf.drawString(360, y, "Detected At")

    y -= 18

    pdf.line(45, y + 8, 560, y + 8)

    pdf.setFont("Helvetica", 10)

    threats = ThreatLog.query.order_by(
        ThreatLog.detected_at.desc()
    ).all()

    for threat in threats:

        pdf.drawString(
            50,
            y,
            str(threat.filename)
        )

        pdf.drawString(
            250,
            y,
            str(threat.severity)
        )

        pdf.drawString(
            360,
            y,
            str(threat.detected_at)
        )

        y -= 18

        if y < 70:

            pdf.showPage()

            y = height - 50

            pdf.setFont("Helvetica", 10)

    pdf.setFont("Helvetica-Oblique", 9)

    pdf.drawString(
        150,
        25,
        "Generated by CloudShield AI • Confidential Report"
    )

    pdf.save()

    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="CloudShield_Enterprise_Report.pdf",
        mimetype="application/pdf"
    )


# =====================================================
# EXCEL REPORT
# =====================================================

@report.route("/report/excel")
@login_required
def generate_excel():

    workbook = Workbook()

    sheet = workbook.active

    sheet.title = "Threat Report"

    sheet.append([
        "Filename",
        "Severity",
        "Detected At"
    ])

    threats = ThreatLog.query.order_by(
        ThreatLog.detected_at.desc()
    ).all()

    for threat in threats:

        sheet.append([
            threat.filename,
            threat.severity,
            str(threat.detected_at)
        ])

    output = BytesIO()

    workbook.save(output)

    output.seek(0)

    return send_file(
        output,
        as_attachment=True,
        download_name="CloudShield_Report.xlsx",
        mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )